# Generated by Django 6.0.3 on 2026-03-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
