# Generated by Django 6.0.3 on 2026-03-23 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_character_image_url_alter_character_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='character',
            name='video_url',
        ),
        migrations.CreateModel(
            name='CharacterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='anime.character')),
            ],
        ),
    ]
