# Generated by Django 6.0.3 on 2026-03-23 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_character_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
