# Generated by Django 6.0.3 on 2026-03-23 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_character_favorites_character_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='video_url',
        ),
        migrations.CreateModel(
            name='CharacterVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(max_length=500)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='anime.character')),
            ],
        ),
    ]
