# Generated by Django 5.2.12 on 2026-03-29 01:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0008_alter_chatthread_options_character_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_bonus_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="profile",
            name="scrolls",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
