# Generated by Django 5.2.12 on 2026-03-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0009_profile_last_bonus_date_alter_profile_scrolls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatthread",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.AddField(
            model_name="character",
            name="summon_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="current_mood",
            field=models.CharField(default="Neutral", max_length=50),
        ),
        migrations.AddField(
            model_name="chatthread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
