# Generated by Django 5.2.12 on 2026-03-29 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0010_alter_chatthread_options_character_summon_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="character",
            options={"ordering": ["-summon_count"]},
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="character",
            name="origin_series",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="character",
            name="signature_move",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatthread",
            unique_together={("user", "character")},
        ),
        migrations.DeleteModel(
            name="CharacterVideo",
        ),
    ]
