# Generated by Django 5.2.12 on 2026-04-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0014_remove_chatmemory_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="wallpaper_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="scrolls",
            field=models.PositiveBigIntegerField(default=100),
        ),
    ]
