# Generated by Django 5.2.12 on 2026-04-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0016_alter_profile_scrolls_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="wallpaper_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="characterimage",
            name="image_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="charactervideo",
            name="video_url",
            field=models.TextField(),
        ),
    ]
